### ISSUE TITLE
Issues with 'combined document' filed by appellate court, and subsequent filings to the same case not showing up in CourtListener

### ISSUE THREAD

**Issue by DXXS** [freelawproject/courtlistener#3822] opened 2024-02-24 23:23 UTC
Recent filings to this appellate case (https://ecf.ca10.uscourts.gov/n/beam/servlet/TransportRoom?servlet=CaseSummary.jsp&caseNum=23-1197&dktType=dktPublic&incOrigDkt=Y&incDktEntries=Y) have stopped showing up in CourtListener; after the district court apparently chose to misinterpret part of a previous filing as the 'mandate' when it clearly wasn't, in  attempting to make available subsequent case filings in an appeal to 'CourtListener', there seems to be some difficulty with accessing the court's latest filing of 2.13.2024, which in viewing it, appears unusually to be some sort of 'combined document' : 010110999623 & 010110999625, only the last number of which appears to be currently listed on CourtListener itself.  I have viewed both documents individually with 'Recap Upload' on, but nothing has shown up.  If I instead opt to view the 'combined document', there is a message at the bottom indicating that it won't be uploaded via 'Recap' if I do!?!?

https://ecf.ca10.uscourts.gov/n/beam/servlet/TransportRoom?servlet=CaseSummary.jsp&caseNum=23-1197&dktType=dktPublic&incOrigDkt=Y&incDktEntries=Y

https://www.courtlistener.com/docket/68130190/shaver-v-whittier-condominiums-hoa/ 

Further, later filings have apparently stopped showing up on 'CourtListener' at all, even after viewed with recap upload on.  In searching outstanding issues, it currently looks to me like this issue may be associated with #765, and/or #711 (?)

**Comment by mlissner** [comment] 2024-02-27 02:03
@ERosendo can you take a look at this one, please?

**Comment by ERosendo** [comment] 2024-02-27 14:52
Hi @DXXS, thanks for your report. I reviewed this issue and here are my findings:

1. I reviewed the uploads for this case around the time of your report and noticed that the CL docket report was missing some entries, including the one you're trying to make available. Uploading documents directly to CL won't automatically create corresponding docket entries. To make new entries visible in CL, you need to upload an updated docket report that includes the missing filings.

2. Our records show that we got the attachment page and the documents you submitted through the recap extension but you didn't upload a docket report. While the documents were successfully uploaded, they were not visible because we needed the docket entry to associate them with the case. The attachment page also requires the docket entry to be displayed.

3. I used the Recap extension to upload the docket report and the previously missing filings now appear correctly in CL. Fortunately, we didn't need to purchase any additional documents as they were already available in our database.

> appears unusually to be some sort of 'combined document' : 010110999623 & 010110999625

I think you may be under this impression because the court uses the `document id` as entry numbers, and the PDFs display the `document id` instead of the usual `document_number-attachment_number` format in the header. However, in cases where the court system doesn't use sequential numbers to identify their filings, it's normal for the PDF headers to display just the `document id`.

**Comment by mlissner** [comment] 2024-02-27 16:46
Thanks for the analysis. To be clear, are there any bugs we think we can solve here?

**Comment by ERosendo** [comment] 2024-02-27 16:57
> To be clear, are there any bugs we think we can solve here?

I don't think so. We just needed a docket report that included the missing filings to create the entries.

**Comment by DXXS** [comment] 2024-02-27 23:40
I think that I had also uploaded their previous order of 01/02/2024 (which they now appear to have ordered ~expunged from the record!?  I guess it may be fortunate that I attached a copy to my filing of 01/16 which had pointed out other filing changes/tampering), that did not have the 'combined document' option at all (which this one still has as an option if one views the item in 'pacer').

**Comment by DXXS** [comment] 2024-02-28 00:49
FWIW, 'Recap' keeps asking me for permission to access sites other than the one that I'm on, and I've seen it fail to show the uploaded icon in pacer dockets unless I do!?  I've also viewed the filing of 01/16 (at a reported cost of $3), but it apparently didn't upload properly to 'Recap'.

**Comment by mlissner** [comment] 2024-02-28 00:54
Sorry, can you provide a screenshot of what you mean by asking for permissions?

**Comment by ERosendo** [comment] 2024-02-28 00:57
@DXXS To help us troubleshoot the issue, please provide the following information:

1. Which browser are you using?
2. What version of the extension do you have installed?

**Comment by DXXS** [comment] 2024-02-28 03:14
Currently using OSX Safari 17.3, Recap 2.4.2 installed

**Comment by DXXS** [comment] 2024-02-28 03:19
<img width="458" alt="RecapSS" src="https://github.com/freelawproject/courtlistener/assets/1892315/144dd486-df5b-484b-a9a2-5f17f075e8a6">

**Comment by mlissner** [comment] 2024-03-01 07:11
@ERosendo, you don't have a way of verifying this, do you? @DXXS, I suspect this has something to do with your problems, and that it's something to do with your system. Nobody else has reported this problem, and it seems like on that would be reported a lot.

That said, it'd still be nice to get to the bottom of it.

**Comment by ERosendo** [comment] 2024-03-01 12:18
> you don't have a way of verifying this, do you?

No, we don't. 

@DXXS Could you please update your extension to the latest version? I've been testing Recap v2.5.0 on Safari 17.3.1 and haven't been able to reproduce the issue.

**Comment by DXXS** [comment] 2024-03-13 04:13
I have recently* tested it with the 2.5.0 version, and most problems appear to have been ~resolved (and files which had been viewed are now showing as having been uploaded via recap), though for some reason when I visit other sites which it had been requesting access to & click on the gray 'Recap' icon, it turns blue, and allows me to turn on upload (but apparently doesn't remember it).

*I have been somewhat busy, having also now filed for U.S.C certiorari, but though I am not seeing a courtlistener interface to viewing same, it does appear that they have their own ~similar (perhaps a link might be nice?).

**Comment by mlissner** [comment] 2024-03-14 23:50
So, sounds like we're safe to close this, @DXXS?

**Comment by DXXS** [comment] 2024-03-15 01:07
Although most symptoms appear to have been addressed in the later version, If I were y'all, I would not necessarily be removing pdf's that had already been uploaded just because judges requested the clerk '...remove the PDF per this court's order...' to cover up their mistakes...

**Comment by mlissner** [comment] 2024-03-16 00:18
Thanks. We're pretty cognizant of the concerns there, and we don't remove much. In general, if there's a public interest in a doc, we'll leave it up. 

Closing for now, but thanks for reporting.

**Closed by mlissner** 2024-03-16 00:18 UTC
