### ISSUE TITLE
Make the front page more useful for lawyers

### ISSUE THREAD

**Issue by elliottash** [freelawproject/courtlistener#491] opened 2016-04-20 17:37 UTC
The front page of CourtListener is dominated by a lot of information that has low use value to practicing attorneys. We should move closer to what WestLaw, Lexis, and Bloomberg Law do.

**Comment by mlissner** [comment] 2016-04-28 21:15
I'd love more details here, @ellliottt, as to what you think would make it more useful. 

One thing I've been thinking about is that it does a terrible job getting people introduced to Oral Arguments and Judges. This didn't happen to me frequently with oral arguments, but with judge search, I've consistently wanted to look somebody up and it's actually NOT possible from the homepage.

**Comment by ellliottt** [comment] 2016-04-29 14:31
I don't have an account on lexis or westlaw right now, but i think we should get some screenshots of their interfaces and focus-group some practicing attorneys about how they use them.

**Comment by anseljh** [comment] 2016-04-29 21:56
Here's what Westlaw looks like when you log in. I think the main things to note are that they break things down by **kind** of content (cases [opinions], forms, briefs,etc. etc.), by **source** of content (federal, state), and by **practice area**. The search box remains very prominent, of course. The "Favorites" area is actually useful, because a practitioner will go back to certain resources a lot and it's nice to have them right there when you log in.

I don't have Lexis anymore, but I recall it was more or less the same idea but a little clunkier.

![2016-04-29-westlaw-home](https://cloud.githubusercontent.com/assets/2075772/14930603/094118c4-0e1a-11e6-867f-4b205eca3b36.png)

**Comment by mlissner** [comment] 2016-04-29 22:00
@anseljh Can I bug you for a scrolled screenshot and edit your post to share that one? If you go into dev tools there's a camera you can [turn on in the settings][d].

[d]: https://developer.mozilla.org/en-US/docs/Tools/Tools_Toolbox#Settings

**Comment by mlissner** [comment] 2016-04-29 22:45
OK, so I think the biggest thing we should probably do is introduce a second navigation bar below the main one, kind of like Google does: 

![screenshot from 2016-04-29 15 37 49](https://cloud.githubusercontent.com/assets/236970/14931443/5a31c750-0e20-11e6-92b2-e4beb44f3438.png)

That, in itself, would free us up to put many more links on every page. A big problem right now is that we only have space for a few links in the bar we have. If we had another bar down there, we could easily put links to the visualizations, oral arguments, people db, podcasts, and whatever other features we come up with.

As that affects the homepage, we should change the search bar to be something like what West has, where you can search different object types via a drop down. Then, on the homepage, we just have to tweak the advanced search section to show the right fields for the right object type -- or we need to create new advanced search pages for each object type. That might be a good idea anyway.

One other comment: I'm just throwing ideas around, but we need to make sure that the homepage continues to convey recency. I.e. that there's new material every day and that there are new features coming along. Maybe more links to the blog or something would help. That'd make the connection to FLP stronger too.

I'm wide open to ideas. The version we have was thrown together pretty quickly.

**Comment by karlnicholas** [comment] 2016-05-17 19:34
I'd like to chip in here and suggest that such an effort is not well aligned with what I see as CourtListener's core functionality, which at this point s simply providing cases. To whom, exactly, that functionality is useful is a different question, though I know it's useful to me. I've been working on an application along the lines of the this issue, i.e., something more useful for attorneys, but as a someone with a paralegal certification I can tell you that while westlaw/lexus-nexus is invaluable to the profession the use case is fairly limited, meaning it will never be the 'next killer app'. 

Also, if should be noted that the problem is much, much, much more complicated than first meets the eye. That's not to say that it's impossible to take business away from westlaw/lexus, but it would require a game changer that, due to the nature of the judiciary, is unlikely to be obvious. In other words, the judiciary is a human run thing, and computers aren't going to be able to emulate even how things are currently being handled. While there may be opportunities to create "specialty apps" that might one day be bought out by westlaw/lexus, such an app will come from out of the box thinking rather than "lets do something like westlaw." 

Please don't take these comments the wrong way. I encourage and appreciate what you're saying, but I'd rather see you thinking in a different direction.

**Comment by mlissner** [comment] 2016-05-17 20:35
Appreciate the comments, @karlnicholas. I don't think we'll be slavish to the design of West/Lexus. They're interesting to see, because they'll provide design inspiration, but we'll go where our strengths and our users take us.

What would you want to see on the homepage?

**Comment by karlnicholas** [comment] 2016-05-17 22:05
I don't really have much of an opinion (pun?) on what I'd like to see. As a user, I'm pretty much interested in accessing digital copies. As I was saying, typical use cases for Legal materials are fairly limited, opinions especially so. The public doesn't really understand what these opinions are actually saying and attorneys are mostly using practice guides. I think the non legal value of the opinions are much more interesting. Google recently opened up a natural language processing API. IBM has that Watson neural network API. In a way, these opinions represent the ultimate AI challenge. For example, judges are well known (in the judiciary anyway) of carefully choosing their words and language and using a great deal more obscure words and precise language. Opinions may help language processors become better. I recently got an email on [A Visual Representation of Predictive Coding Case Law](http://logikcull.com/blog/a-visual-representation-of-predictive-coding-case-law/). Haven't looked that close on how they did it, this kind of graphic is similar to graphics I have already seen on the CourtListener website. These networks are the kind of thing I have been playing with, but only as an amateur. The graphic in the above link implies an understanding of what's *in* the case, not just the interconnected citations.

**Comment by mlissner** [comment] 2016-08-17 16:40
Secondary navigation bars were added today in issue #529. It's one step in the right direction for this ticket, but until we have more concrete changes that we want to make, I'm not sure how to resolve this issue. Happy to improve the homepage, but I need more direction first. What exactly do we want to add/remove to the homepage? What features are missing that need to be built?

**Comment by mlissner** [comment] 2023-04-24 23:20
Closing this as a dup of #1271.

**Closed by mlissner** 2023-04-24 23:20 UTC
Labels: enhancement
