### ISSUE TITLE
'Min Cites' filter causes "deadly error"

### ISSUE THREAD

**Issue by brianwc** [freelawproject/courtlistener#337] opened 2015-05-18 03:58 UTC
1. Enter a search query. Example 'copyright'.
2. On the results page, enter a number in the 'Min Cites' box, such as '5' and click search.
3. Deadly error results.

**Comment by mlissner** [comment] 2015-05-18 17:42
Here's the log entry that shows the error: 

```WARNING 2015-05-18 10:39:28,502 (/var/www/court-listener/alert/search/views.py do_search): "Error loading search page with request: <QueryDict: {u'q': [u''], u'stat_Precedential': [u'on'], u'order_by': [u'score desc'], u'cited_gt': [u'3']}>"
WARNING 2015-05-18 10:39:28,502 (/var/www/court-listener/alert/search/views.py do_search): "Error was ({'transfer-encoding': 'chunked', 'status': '400', 'content-type': 'application/xml; charset=UTF-8'}, '<?xml version="1.0" encoding="UTF-8"?>\n<response>\n<lst name="responseHeader"><int name="status">400</int><int name="QTime">1</int><lst name="params"><str name="caller">facet_parameters</str><str name="facet">true</str><str name="facet.mincount">0</str><str name="q">*:*</str><str name="facet.field">{!ex=dt}status_exact</str><arr name="fq"><str/><str>citeCount:[3 TO ]</str><str>court_exact:("wash" OR "iowactapp" OR "tax" OR "oklacivapp" OR "ca6" OR "reglrailreorgct" OR "illinoised" OR "mosd" OR "cafc" OR "ndctapp" OR "moctapp" OR "mdctspecapp" OR "mass" OR "insb" OR "pa" OR "insd" OR "mich" OR "washctapp" OR "kyeb" OR "kyed" OR "lamd" OR "ohioctapp" OR "wis" OR "scotus" OR "arkctapp" OR "pawb" OR "kywb" OR "pawd" OR "kywd" OR "alacivapp" OR "cod" OR "cob" OR "kyctapp" OR "flsd" OR "tnmd" OR "tnmb" OR "flsb" OR "ctb" OR "waeb" OR "ctd" OR "wawd" OR "wawb" OR "pacommwct" OR "flmb" OR "txed" OR "txeb" OR "tex" OR "alaska" OR "njb" OR "cusc" OR "paed" OR "paeb" OR "ded" OR "deb" OR "arwb" OR "idaho" OR "del" OR "arwd" OR "ariztaxct" OR "tennessed" OR "indctapp" OR "waed" OR "txsd" OR "ga" OR "haw" OR "nd" OR "nc" OR "nm" OR "nj" OR "nh" OR "ny" OR "tennesseeb" OR "bap9" OR "oklaag" OR "missctapp" OR "mdd" OR "mdb" OR "ared" OR "alnd" OR "alnb" OR "areb" OR "tenncrimapp" OR "kanctapp" OR "txnb" OR "txnd" OR "fiscr" OR "usjc" OR "nynb" OR "nynd" OR "nhb" OR "iasb" OR "delsuperct" OR "tnwb" OR "sdb" OR "sdd" OR "hawapp" OR "utb" OR "nywd" OR "ncctapp" OR "nywb" OR "fla" OR "ohioctcl" OR "texcrimapp" OR "txwd" OR "txwb" OR "me" OR "mnd" OR "mnb" OR "nced" OR "nceb" OR "colo" OR "tned" OR "tneb" OR "ca11" OR "ca10" OR "almd" OR "almb" OR "connappct" OR "oklacrimapp" OR "bap1" OR "bap2" OR "bap6" OR "ncwb" OR "bap8" OR "ncwd" OR "vactapp" OR "ca5" OR "ca4" OR "ca7" OR "ndd" OR "ca1" OR "ndb" OR "ca3" OR "ca2" OR "ca9" OR "ca8" OR "nmib" OR "nysb" OR "nysd" OR "nmid" OR "southcarolinaed" OR "gamd" OR "wvsb" OR "nvb" OR "wvsd" OR "nvd" OR "ind" OR "gamb" OR "cal" OR "pamd" OR "michctapp" OR "bap10" OR "pamb" OR "eca" OR "dc" OR "miwd" OR "prb" OR "okla" OR "cc" OR "nyeb" OR "orb" OR "ord" OR "southcarolinawd" OR "prd" OR "idahoctapp" OR "nyed" OR "hid" OR "hib" OR "indtc" OR "ilsd" OR "ccpa" OR "ilsb" OR "cadc" OR "jpml" OR "nmb" OR "cacd" OR "nmd" OR "cacb" OR "miwb" OR "nyappdiv" OR "utahctapp" OR "rib" OR "rid" OR "mieb" OR "mied" OR "va" OR "nmctapp" OR "deljudct" OR "gactapp" OR "wisctapp" OR "armfor" OR "pasuperct" OR "vtd" OR "vtb" OR "mocd" OR "miss" OR "fisc" OR "illinoisd" OR "or" OR "alsd" OR "alsb" OR "ncmd" OR "ala" OR "ncmb" OR "tnwd" OR "gasb" OR "gasd" OR "wied" OR "wieb" OR "canalzoned" OR "iasd" OR "laed" OR "nhd" OR "dcb" OR "dcd" OR "ariz" OR "tennctapp" OR "ohnd" OR "cavc" OR "ri" OR "pennsylvaniad" OR "alaskactapp" OR "minnctapp" OR "txsb" OR "arizctapp" OR "bapma" OR "ganb" OR "bapme" OR "alactapp" OR "la" OR "azd" OR "tenn" OR "ilnd" OR "ilnb" OR "cit" OR "afcca" OR "cjdpa" OR "ohiod" OR "vaeb" OR "vaed" OR "innd" OR "innb" OR "texapp" OR "lamb" OR "ohnb" OR "ky" OR "wyo" OR "wyb" OR "wyd" OR "njd" OR "flmd" OR "ohio" OR "neb" OR "ned" OR "asbca" OR "nev" OR "scb" OR "scd" OR "mtd" OR "mtb" OR "vid" OR "vib" OR "vawd" OR "wiwd" OR "wiwb" OR "vawb" OR "idb" OR "idd" OR "mssb" OR "mssd" OR "lawd" OR "lawb" OR "wvnb" OR "conn" OR "wvnd" OR "nmcca" OR "cand" OR "nyfamct" OR "canb" OR "njtaxct" OR "mad" OR "mab" OR "stp" OR "utah" OR "delctcompl" OR "caeb" OR "caed" OR "msnb" OR "msnd" OR "delfamct" OR "njsuperctappdiv" OR "wva" OR "mspb" OR "gand" OR "fladistctapp" OR "alacrimapp" OR "scctapp" OR "mont" OR "sd" OR "minn" OR "sc" OR "connsuperct" OR "uscfc" OR "indianad" OR "oknb" OR "oknd" OR "moeb" OR "moed" OR "ark" OR "utd" OR "okeb" OR "arb" OR "acca" OR "oked" OR "lactapp" OR "kan" OR "nebraskab" OR "meb" OR "med" OR "mowb" OR "mowd" OR "mc" OR "flnb" OR "iand" OR "ianb" OR "flnd" OR "akd" OR "akb" OR "okwb" OR "okwd" OR "delch" OR "laeb" OR "bva" OR "massappct" OR "coloctapp" OR "calctapp" OR "ilcd" OR "californiad" OR "ilcb" OR "oklacoj" OR "ksb" OR "oklajeap" OR "ksd" OR "casd" OR "texreview" OR "casb" OR "orctapp" OR "gud" OR "nysurct" OR "gub" OR "ill" OR "vt" OR "ohsb" OR "ohsd" OR "md" OR "illappct" OR "mo" OR "iowa" OR "nebctapp")</str><str>{!tag=dt}status_exact:("Precedential")</str></arr><str name="rows">0</str></lst></lst><lst name="error"><str name="msg">org.apache.solr.search.SyntaxError: Cannot parse \'citeCount:[3 TO ]\': Encountered " "]" "] "" at line 1, column 16.\nWas expecting one of:\n    &lt;RANGE_QUOTED&gt; ...\n    &lt;RANGE_GOOP&gt; ...\n    </str><int name="code">400</int></lst>\n</response>\n')"```

Should be fairly simple looks like the problem is in:

> SyntaxError: Cannot parse \'citeCount:[3 TO ]\'

Which should instead be: 

> citeCount:[3 TO *]

We generate these queries in a function in search_utils.py. This should be fairly simple to fix, I think, but a tests for the function would be good to prevent regressions.

Mike

**Comment by mlissner** [comment] 2015-08-19 17:28
Was easy. Committed and will land in due time. Leaving open until verified.

**Closed** 2016-01-20 19:27 UTC
Labels: bug, in-dev-version
