### ISSUE TITLE
Make even Shorter Links Possible

### ISSUE THREAD

**Issue by brianwc** [freelawproject/courtlistener#333] opened 2015-04-22 17:03 UTC
https://www.courtlistener.com/opinion/599277/fantasy-inc-v-fogerty/
and
https://www.courtlistener.com/opinion/599277/blah-blah-blah-put-whatever-you-want-here/
and
https://www.courtlistener.com/opinion/599277/go/
all resolve to the same case. It only matters that SOMEthing be in the slug and CL knows which opinion to pull up. Would be nice if it also worked with no slug at all. That is, THIS link does not resolve:
https://www.courtlistener.com/opinion/599277/ 
and would be nice if it did for purposes of Twitter-posting.

**Comment by mlissner** [comment] 2015-04-22 18:44
This is probably a good call and should be easy to do, but Twitter at least auto-shortens now so it doesn't matter there, and I'm a bit concerned how this would affect the `cited-by` and `authorities` pages, which currently live at:

    /opinion/$number/$slug/cited-by/

and 

    /opinion/$number/$slug/authorities/

Probably not a big issue, but something to watch out for. 

I'm not sure I understand the use-case though, with auto-shortening being done these days by Twitter.

**Comment by brianwc** [comment] 2015-04-22 19:06
I'm not saying Twitter makes sense, but I am saying that they let me post a link that was courtlistener.com/opinion/599277/ but would not let me post courtlistener.com/opinion/599277/go/ because it was 3 characters longer. And then, of course, they did use their own url shortener on it, but that--for some bizarre reason--did not change how they did their character counts when posting. This is a general rule I've learned: Don't assume that software developed by Twitter does what rational software would do.

**Comment by mlissner** [comment] 2015-08-04 01:06
Since the only reason for this request is a bug in Twitter that I don't think we can reproduce, I'm closing this one.

**Closed by mlissner** 2015-08-04 01:06 UTC
Labels: enhancement, help wanted
