### ISSUE TITLE
Searching for a docket number with initials should return the docket

### ISSUE THREAD

**Issue by ikeboy** [freelawproject/courtlistener#1394] opened 2020-08-30 00:16 UTC
Example: https://www.courtlistener.com/?type=r&q=1%3A17-cv-08603-JSR&type=r&order_by=score%20desc

No results. But it should return https://www.courtlistener.com/docket/6218685/stevens-v-vodka-milk-llc/, at least. Preprocess the docket number to remove the ending initials, perhaps?

**Comment by mlissner** [comment] 2020-08-30 16:37
Seems like a good idea to me. Want to take a stab at it?

**Comment by mlissner** [comment] 2023-04-24 21:47
Duplicate of: https://github.com/freelawproject/courtlistener/issues/764

**Closed by mlissner** 2023-04-24 21:47 UTC
Labels: search
