### ISSUE TITLE
Citation Parsing Fails on OLD CASES

### ISSUE THREAD

**Issue by Colinstarger** [freelawproject/courtlistener#409] opened 2015-12-30 23:25 UTC
In the interest of gathering specific examples where the parser fails with old cases. Here is a list that I will try to update.

(1) In [HEIEN](https://www.courtlistener.com/opinion/2760668/heien-v-north-carolina/), the parser misses the cite to [BRINEGAR](https://www.courtlistener.com/opinion/104716/brinegar-v-united-states/). Here is what the text that should be picked up looks like:
To be reasonable is not to be perfect, and so the
Fourth Amendment allows for some mistakes on the part
of government officials, giving them “fair leeway for en-
forcing the law in the community’s protection.” Brinegar
v. United States, 338 U. S. 160, 176 (1949).

(2) In [CSX II](https://www.courtlistener.com/opinion/2783887/alabama-dept-of-revenue-v-csx-transp-inc/), the parser misses the cite to [CSX I](https://www.courtlistener.com/opinion/219508/csx-transp-inc-v-mcbride/?q=csx&order_by=score+desc&stat_Precedential=on&court=scotus). Here's what the text that should pick it up looks like:
This Court held that a tax “discrimi-
  nates” under subsection (b)(4) when it treats “groups [that] are simi-
  larly situated” differently without sufficient “justification for the dif-
  ference in treatment,” CSX Transp. v. Ala. Dept. of Revenue, 562
  U. S. 277, 287 (CSX I). 

The only thing that I see in common between the two cases is that the cite is broken up by a carriage return. Could that be messing things up? (I had previously thought the extra space in "U. S." might be a problem, but I have since found plenty of instances where the parser DOES pick that up).

Note this error is different from the known problem of picking up cites to NEW cases with weird cites like 123 S.Ct. ___ or etc. (the ___ problem).

**Comment by mlissner** [comment] 2016-02-18 01:12
Got it. It's not that we weren't able to parse out the citations from the text. It's not that once parsed out we were unable to figure out which case the citation was referring to. No. Indeed, if you look at [the authorities for Heien][1], you'll see that it references Bringar just fine. 

So the value is in the DB, but it's not highlighted in the text. Why? Because it's in the text as `U. S.` with a space, and when we try to make that into a link we fail. 

Yay! I've figured out where the bug is occurring and it's a very small part of the code. Tomorrow I'll see if a fix is possible. Of course, if we want to fix these links in the existing content...we'll have a big task ahead of us.

1: https://www.courtlistener.com/opinion/2760668/heien-v-north-carolina/authorities/?

**Comment by Colinstarger** [comment] 2016-02-18 18:07
Thanks Mike (at least I hope this email gets sent to Mike!).

When we do our code tour, this is one area that I'd very much like to visit.

-C

**Comment by mlissner** [comment] 2016-02-18 18:15
Message received, @Colinstarger. Glad to see your masochism is up to snuff for the challenge.

**Comment by Colinstarger** [comment] 2016-02-18 18:26
Ha. Masochism hurts so good. I just want to see what I'd be up against. My more realistic goal is to write something that queries the DB using the API and automatically generates tables similar to my 2014 Term table. This other "job" I have as a "professor" keeps on getting in the way though. So annoying.

**Comment by mlissner** [comment] 2016-02-18 19:46
All fixed including a regression test. Only problem is we'll have to re-run the citation parser to get the fix. Since this only affects the text of the opinion and not any of the other features (like CiteGeist, citation searching, etc), I'm going to leave this be until we find another reason to re-run the citation parser.

**Closed by mlissner** 2016-02-18 19:46 UTC
Labels: citator

**Comment by Colinstarger** [comment] 2016-02-18 19:50
Ok, excellent. Makes sense not to run the whole parser process again. Is it possible to run the parser on specific cases as they arise?

**Comment by mlissner** [comment] 2016-02-18 20:07
It's not terribly difficult to do that.
