### ISSUE TITLE
Missing opinions in Elastic

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#4722] opened 2024-11-21 19:37 UTC
https://www.courtlistener.com/?q=court_id%3Amass

It appears that when performing a search on Courtlistener for Mass court cases using the query court_id:mass, the initial results in Elastic are all 404 errors. I noticed that the first missing case is in our system, but under a different/later cluster id.  I do not recall any deletions for cases so I'm not sure what is going on here. 

All of these are missing.  

![Image](https://github.com/user-attachments/assets/8d51053a-c713-490d-91a0-4fcfbbda01e6)

**Comment by mlissner** [comment] 2024-11-21 20:13
Not great! We had another issue like this, didn't we?

**Comment by mlissner** [comment] 2024-11-21 22:29
Looks like this is a duplicate of https://github.com/freelawproject/courtlistener/issues/3967

**Comment by mlissner** [comment] 2024-12-03 02:52
Seems to be fixed. Closing, but please reopen if I've missed something.

**Closed by mlissner** 2024-12-03 02:52 UTC
