### ISSUE TITLE
Search by judge name doesn't work as expected

### ISSUE THREAD

**Issue by heliostatic** [freelawproject/courtlistener#338] opened 2015-06-04 01:53 UTC
It seems like maybe the search by judge doesn't work as expected if the case was heard by a panel of judges? A free text search for "Madeline Hughes Haikala" returns four cases for which she was a judge, but the same search using the advanced "Judge" field returns no results. This was unexpected.

**Comment by mlissner** [comment] 2015-06-08 18:02
You're right, the judge field is a bit of a hack. When we imported a big collection a year or so ago, we extracted the judge values in any way we could and put them in a free text field. The problem is that since then we don't have a way of identifying this information, so some opinions work properly while others didn't get the metadata we needed. 

That's the bad news. The good news is that we're going to fix this for a few million cases this summer if all goes well. 

Thanks for getting this filed. Hopefully we'll return to it soon and say, "Fixed by way of *\<major-new-feature\>*"

**Closed** 2017-02-09 22:54 UTC

**Comment by heliostatic** [comment] 2017-02-09 22:55
Looks like this is still an issue for "Madeline Hughes Haikala", but sounds like the larger issue is resolved?

**Comment by mlissner** [comment] 2017-02-09 22:59
Yeah, I figured I'd close because there's not a lot more we can do here. For example, we've got a profile page for that judge:

https://www.courtlistener.com/person/1323/madeline-hughes-haikala/

But it doesn't show her as the author of any opinions because we lack the metadata on her opinions to identify her as the author. In general, the system is working though...it's just a limitation of the data, but data improvements are happening constantly, so this will probably just get fixed one day, without needing to track it specifically.
