### ISSUE TITLE
Reorganize bulk data to make it easier to use

### ISSUE THREAD

**Issue by elliottash** [freelawproject/courtlistener#634] opened 2017-01-12 10:17 UTC
This is a big project but worth doing.

For example, the bulk opinions data has an "author" field, but it is a link to the people DB API. This is nice but there should be a normalized judge name too, so one doesn't have to do the extra step. On the other hand "clusters" has the judges slug string.

Also, there could be a much leaner version of the bulk data that would have most of what researchers/developers would want.

**Comment by mlissner** [comment] 2017-01-12 20:01
Oh dear! This sounds like a big one indeed, but if the bulk data isn't useful, that's certainly worth addressing.

>  the bulk opinions data has an "author" field, but it is a link to the people DB API. This is nice but there should be a normalized judge name too, so one doesn't have to do the extra step.

I think the assumption here is that if you're working with the bulk data, you'd have the judge data downloaded too, and the extra step is fairly easy to do locally. Otherwise, the problem becomes: Where do you draw the line? You can add the judge name, but how is that really more useful? I assume most research involves the facts about a judge, not their name, so really what you'd want is all of *that* information (which could include Positions, ABA Ratings, Political Affiliations...)

That said, our API library makes it possible to embed objects within other objects when you make the bulk data—ie, we could embed a Person object into an Opinion object instead of having the reference via the link, but the problem is performance. It makes the data bigger (the Person data is now copied into every single Opinion), and it makes the query more complex when you are generating the JSON objects for the Opinions (which already takes around 24 hours to do).

> On the other hand "clusters" has the judges slug string.

Ideally though, that field isn't very useful, right? Like, ideally, you'll get the same info, normalized, in the Opinion fields?

> Also, there could be a much leaner version of the bulk data that would have most of what researchers/developers would want.

Interesting. I wouldn't be opposed. Leaner is faster to create than the fatter thing proposed above! 

Anyway, I guess all of this is to say I'm open to being persuaded, but it's quite a complicated beast.

**Comment by mlissner** [comment] 2023-10-26 18:23
A lot has changed in the last six years and I don't think we have plans to tweak the bulk data further. Closing for now.

**Closed by mlissner** 2023-10-26 18:23 UTC
