### ISSUE TITLE
Judge is not being assigned to RECAP dockets.

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#2819] opened 2023-06-13 18:20 UTC
While investigating #2817, we discovered that some of the RECAP dockets provided in the sample do not have an assigned judge. However, looking at these dockets in PACER, the judge's information is available.

It appears that we're parsing the judge information for district and bankruptcy dockets, but for some reason, it is not being saved in the docket.

An example:

https://www.courtlistener.com/docket/38228028/linda-l-swilley/
https://ecf.ilsb.uscourts.gov/cgi-bin/DktRpt.pl?260496784257687-L_1_0-1

![Screenshot 2023-06-13 at 12 19 33](https://github.com/freelawproject/courtlistener/assets/486004/e6a7c165-b45f-45ff-b691-57ea9d2376ff)

**Comment by mlissner** [comment] 2023-06-18 12:29
Hm, I see this is In Review?

**Comment by albertisfu** [comment] 2023-06-19 15:40
Oh, no sorry, I think it was a mistake while checking my backlog. This should be in the backlog column. I'll be working on it.

**Comment by albertisfu** [comment] 2023-06-22 21:55
Ok, I've reviewed this and it seems that this is not related to a current parsing issue.

I examined some of the reported dockets, and after purchasing the docket in PACER, it displayed the assigned judge correctly:

https://www.courtlistener.com/docket/38228028/linda-l-swilley/
https://www.courtlistener.com/docket/67079107/kenneth-edward-walker/
https://www.courtlistener.com/docket/8036521/kevin-dion-jones/
https://www.courtlistener.com/docket/14624022/john-francis-wodecki/

The problem seems to be that the original source of these dockets was the RSS feed that doesn't contain the Judge's name.

Since this issue is not a bug on our end, it could be closed.

**Comment by arharvard** [comment] 2023-06-22 22:11
So just to make sure I understand, the judge name is not going to appear in the bulk data for this district?

**Comment by albertisfu** [comment] 2023-06-22 23:32
That's correct. These dockets won't show the judge's name until they are updated with a version that contains the judge's name. For instance, the dockets that I added in a comment above now include the judge's name. They will be shown in the next bulk data update.

Correct me if I'm wrong, @mlissner, but if we pull iQuery data as you mentioned in https://github.com/freelawproject/courtlistener/discussions/2820, we could obtain all of these judges too, and clean up the docket number as well, right? Since iQuery pages contain the judge's name, correct?

**Comment by albertisfu** [comment] 2023-06-22 23:47
I just confirmed that the judge's name is available on `scb` iQuery pages. However, it's not parsed because it is displayed as `Chief Judge` instead of simply `Judge`. Therefore, I will apply a fix for this in Juriscraper.

**Comment by mlissner** [comment] 2023-06-25 01:51
Sounds like this is largely resolved going forward. The issue is that:

2. Many of these dockets were only obtained via the RSS feed, which doesn't include the judge information.

1. This court has an annoying customization of the iquery page we didn't notice before, which made it so we didn't get the data during our last bulk download of the iquery pages. This is fixed going forward via freelawproject/juriscraper#693.

The fix for the existing data is to do a mass iquery download and merge, but unfortunately, we don't have plans to do that any time soon. We could do it as a paid engagement, but we have a lot of irons in the fire right now, so we can't prioritize an iquery download just to fix this one jurisdiction. 

If this is something you'd like to discuss, @arharvard, let's get that conversation going via email. It shouldn't take a ton of work, but it may take some customization and monitoring. Sorry we don't have more resources to do more on this right now. We're really swamped, so we have to be a bit strategic in how we use our time. Happy to chat though.

@albertisfu, do you see anything more to do on this issue, or do you think we can close it?

**Comment by arharvard** [comment] 2023-06-25 11:00
Thanks you for the help and information. 
For the judge issue, I now see I may have not been clear in the original discussion. The issue is beyond SCB (which was an example in the original discussion). I see this repeat in the following courts, where after merging with FJC, at least 45% of judge names are missing (and for most over 90%): 
alsb, arb, caeb, casb, ctb, dcb, hib, idb, ilnb, ilsb, ksb, mowb, ncmb, nebraskab, nhb, nynb, orb, paeb, prb, scb, txeb, utb, wiwb, wvnb.

**Comment by mlissner** [comment] 2023-06-26 15:16
Interesting. Looks like it affects a number of bankruptcy courts. That's good, in that it isn't just a one-off, but too bad, since the impact is greater than we realized. I agree that it'd be really nice to do a big crawl to bring in this data, but we still don't have the resources to do so, unfortunately. (Affecting more cases is a double-edged sword—it means the problem is a bigger priority, but it also means it will be more work to do so.)

Are you sure that's the exhaustive list, in case we do find time to look at this?

**Comment by arharvard** [comment] 2023-06-26 15:22
Okay, thanks for letting me know. 

These are the districts with the biggest issue, the rest have judge assigned to at least 85% of cases.
I do not mind sharing the full list of % missing judges in each district (for bankruptcy) if you would like.

**Comment by mlissner** [comment] 2023-06-26 16:35
No, that's OK. I think having this list will be enough if/when we choose to return to this, but realistically it'll probably be a while until this happens. It's not something we do on a regular basis, unfortunately.

**Closed by mlissner** 2023-06-26 16:35 UTC
