### ISSUE TITLE
Alert on weird corner case: modified opinions

### ISSUE THREAD

**Issue by anseljh** [freelawproject/courtlistener#382] opened 2015-11-14 01:09 UTC
Sometimes opinions are modified after they're first published, but the updated opinion only appends a description of what should be modified in the original opinion.

I am not going to suggest that CL should do the editorial work of making those changes, but it could be a good idea to alert users that there are modifications at the end of the opinion that they might want to look at.

Here's an example from a case I was involved in:
* [Original opinion, filed 12/5/2014](https://www.courtlistener.com/opinion/2758032/jbb-investment-partners-v-fair/)
* [Modified opinion, filed 12/30/2014](https://www.courtlistener.com/opinion/2765531/jbb-investment-partners-v-fair/)

The modified opinion starts with this:

```
Filed 12/5/14; mod. order filed 12/5/14 depublishing opn; pub. & mod. order filed 12/30/14; both orders attached
(see end of opn.)
```

I have no idea how standard that is, if at all.

Also: Should CL remove the original opinion, or mark it as superseded, etc.?

**Comment by mlissner** [comment] 2015-11-14 01:14
Yeah, we're at the point where we *really* need to start detecting near-duplicates automatically. There's too many of them, and the cause all kinds of headaches. I guess when we do that we can tweak the alerts to somehow notify people that an opinion they thought was interesting had changed.

**Comment by mlissner** [comment] 2015-12-16 07:07
I'm going to tackle this in #399, so closing here. Thanks for reporting this @anseljh, it helped it get more priority (though we'll see when it actually begins getting solved).

**Closed by mlissner** 2015-12-16 07:07 UTC

**Comment by mlissner** [comment] 2016-02-19 00:27
@anseljh, I'm looking at this idea more closely and I'm not sure we can do it justice without a lot of effort. 

Two problems:

1. How do we know which cases to notify somebody about? The only way they have of saying they're interested in a case is by favoriting it, but that feature isn't very popular for a number of reasons. So, I suppose if you have an item marked as a favorite and a new version of that item is identified, we could send you an email. 

2. But the larger issue is that we don't send emails based on favorites at this point, so it'd take a fair bit of duct tape to pull that together too...and I'm not sure it's a common enough use case. 

It's an interesting problem, and I'm not sure anybody else is solving it, but I confess we might not be able to solve it in a good way either.

**Comment by anseljh** [comment] 2016-02-19 00:46
e-discovery people might have some ideas about near-dupes. It's hard, though, and I agree, likely not worth your time.

**Comment by mlissner** [comment] 2016-02-19 00:48
Well, the dup algo is coming along (I've dabbled in e-discovery, and it's super needed). But there's no way for us to know which cases to send you emails about. That's the bigger problem.
