### ISSUE TITLE
Google seach finds CL opinion case that CL search does not.

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/courtlistener#733] opened 2017-09-13 20:30 UTC
If I search Google for the phase, "stands in the shoes of the general public," the number one hit is a CL opinion PDF:

```
IN THE COMMONWEALTH COURT OF ... - Court Listener
https://www.courtlistener.com/pdf/2016/09/09/a._brown_v._j._wetzel.pdf
Sep 9, 2016 - State University stands for the principle that '[w]hen the media requests ... then stands in the shoes of the general public.' Id. Inmates do.
```

But If I do the same search via CL, https://www.courtlistener.com/?q=%22stands+in+the+shoes+of+the+general+public%22 

I get no results at all. (And without the quotes, I get 23,000 which is not helpful.)

And if I use the CL recap search, https://www.courtlistener.com/?type=r&q=%22stands+in+the+shoes+of+the+general+public%22&type=r&order_by=score+desc

I get one result, but it's _Fair Housing Council of Oregon v. Travelers Casualty and Surety Company (D. Or. 2015)_, not _Brown v. Wetzel_.

Curiously, none of this is what I expected to get, which was _Pennsylvania State University v. State Employees’ Retirement Board, [935 A.2d 530, 537 (Pa. 2007)]_.

But it seems wrong that Google finds a CL document that CL doesn't. Of course, Google is finding a PDF and maybe that's somehow not in the CL database despite being on the CL website? But it should be within scope?

Thanks.

**Comment by mlissner** [comment] 2017-09-13 21:18
This looks like it has to do with stopwords. Solr is notoriously annoying about this. I think, based on [this post][so], that the solution is to add `enablePositionIncrements` to both the query and the index analyzers. The current issue is that the phrase you're searching for is:

    "stands in the shoes of the general public"

Solr is nuking some of the words in this phrase and leaving others for reasons I don't fully understand yet. This query works:

https://www.courtlistener.com/?q=%22stands+in+the+shoes+general+public%22+wetzel&type=o&order_by=score+desc&stat_Precedential=on

I'm not sure why this is. "in the" needs to be included in the query but "of the" doesn't, but all three words, "in", "of" and "the" are all in the stopwords list. I've tested this before and after re-indexing this document and committing the changes to the index. 

This will take some more research. Thanks for filing.

**Comment by mlissner** [comment] 2023-04-24 22:48
Duplicate of: https://github.com/freelawproject/courtlistener/issues/1635

**Closed by mlissner** 2023-04-24 22:48 UTC
