### ISSUE TITLE
Bulk data outage

### ISSUE THREAD

**Issue by eltrompetero** [freelawproject/courtlistener#2111] opened 2022-06-06 11:34 UTC
I'm getting a 404 error when I try to download data using your bulk data API.

For example, any of the links on this page
https://www.courtlistener.com/api/bulk-info/

such as
https://www.courtlistener.com/api/bulk-data/opinions/ca1.tar.gz

lead to this message
404 U.S. ___, Page Not Found
sorry, that page does not exist…

**Comment by flooie** [comment] 2022-06-06 16:18
Closing this issue and marking it as a duplicate of #1983

**Closed by flooie** 2022-06-06 16:18 UTC
Labels: duplicate
